apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoevolve-backend.fullname" . }}
  labels:
    {{- include "todoevolve-backend.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.appEnv | default "production" | quote }}
  LOG_LEVEL: {{ .Values.logLevel | default "info" | quote }}
