apiVersion: v2
name: todoevolve-frontend
description: TodoEvolve Frontend Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - nextjs
  - frontend
  - todoevolve
  - react

maintainers:
  - name: TodoEvolve Team
    email: team@todoevolve.dev
